### ISSUE TITLE
'Submit' button greyed out on error

### ISSUE THREAD

**Issue by ThomasThelen** [rhizomik/rhizomerEye#68]
If an error occurs while setting up a new endpoint the `Review` button is greyed out, preventing users from trying again. To get around this, I can change any field, and then change it back to what it used to be and the button will be clickable. This might _not_ be a bug if it's expected that the user is supposed to make a change before trying again

To reproduce:
1. Click Datasets > New
2. Fill in misc dataset details
3. Enter an incorrect SPARQL endpoint
4. Click Submit
5. See error
6. Click Review
7. Note that you can't continue again

**Comment by rogargon** [comment]
Yes, that is intended if an error has been generated. Rhizomer is expecting any change in the configuration before it is possible to try again
