### ISSUE TITLE
Able to click submit for a new dataset with invalid endpoint

### ISSUE THREAD

**Issue by ThomasThelen** [rhizomik/rhizomerEye#69]
Super minor issue-but I saw that the endpoint field is red when there's an error but the 'Submit' button is still clickable. From another issue I saw that the Submit button is greyed out on other conditions, so this one may have been overlooked.

<img width="1236" alt="Screen Shot 2022-02-11 at 10 02 19 AM" src="https://user-images.githubusercontent.com/9289652/153644920-e105e139-ff1a-4002-913e-48ecf7bb7d90.png">

After clicking submit, we get the error shown below (expected)

<img width="1235" alt="Screen Shot 2022-02-11 at 10 02 28 AM" src="https://user-images.githubusercontent.com/9289652/153644932-de8d7e12-35a7-4ae2-af49-d4e2360549ac.png">

**Comment by rogargon** [comment]
Thanks, that is right, the Submit button should be disabled if there is an error. We would look into it
