### ISSUE TITLE
demo site dbpedia page reports surprising error

### ISSUE THREAD

**Issue by TallTed** [rhizomik/rhizomerEye#94]
Starting [here](https://rhizomer.rhizomik.net/datasets/dbpedia) and clicking any displayed word, you should see this error appear at the top of the page:
```
Unexpected error making the query: GET http://virtuoso.database:8890/sparql
```

My guess is there's a setting somewhere that sets the target for that `GET` and has a wrong FQDN value (`virtuoso.database`).

Until that's fixed, this page is a poor representation of what rhizomerEye can do.

P.S. There's a typo on the [About page](https://rhizomer.rhizomik.net/about), where it says `Worcloud generated by Rhizomer for DBPedia`. The first word should be `Wordcloud`.

**Comment by rogargon** [comment]
Thanks @TallTed for reporting these issues. The "Unexpected error" was due to a temporal issue with the Virtuoso database serving the DBPedia data.

Regarding the typos in the About page, we have fixed them with commit aa42c6e75ba1a340dec3a3f2eb8294fd5d33f74a
